### ISSUE TITLE
Keyboard shortcuts localization

### ISSUE THREAD

**Issue by ghost** [thunderbird/k-9#2843]
Currently in Transifex two keyboard shortcut strings are hard coded, thus not translatable. These shortcuts. Don't mean anything for non English user, and will thus be harder to memorize. It'd be advisable to make them translatable.

* String 1:
Del (or D) - Delete\nR - Reply\nA - Reply All\nC - Compose\nF - Forward\nM - Move\nV - Archive\nY - Copy\nZ - Mark (Un)read\nG - Star\nO - Sort type\nI - Sort order\nQ - Return to Folders\nS - Select/deselect\nJ or P - Previous Message\nK or N - Next Message
* String 2:
Del (or D) - Delete\nC - Compose\nM - Move\nV - Archive\nY - Copy\nZ - Mark (Un)read\nG - Star\nO - Sort type\nI - Sort order\nQ - Return to Folders\nS - Select/deselect

**Comment by cketti** [comment]
To be clear, the strings can be translated. It's only the key/functionality mapping that is hardcoded.

Even in English some hotkeys have no relation to the name of the functionality they trigger, e.g. "Z - Mark (Un)read". So this is a very low priority item for me.

**Comment by wmontwe** [comment]
Closed as outdated.
