### ISSUE TITLE
Ability to Adjust Dark Theme Colors

### ISSUE THREAD

**Issue by seniorm0ment** [thunderbird/k-9#7251]
The app is a bit too dark for my personal taste, it can make stuff hard to read for me. It would be nice to be able to just customize the colors on different areas. 
Menus, headers, message area, etc.

**Comment by wmontwe** [comment]
Thank you for the feedback. As we're transitioning to Material 3, we're also taking the opportunity to refine our dark and light themes. While full UI customization isn't in the immediate plans, we're open to specific suggestions for theme improvements. Your feedback will be invaluable as we move forward. Any particular changes you'd recommend?

**Comment by seniorm0ment** [comment]
As far as the colors, a lot of apps have a more "AMOLED Black" option, then a "Dark" which is more of a matte. The K9 theme currently leans more towards that AMOLED black, and it can be a bit tough on the eyes.
Also currently I feel the headers are too far in color from the other areas like the message box is a lot lot darker than the header, it doesn't look very uniform.

A more medium gray would be a nice addition. Take a peek at Google Messages maybe, or just the default AOSP Dark Mode. Both a bit lighter and more material

**Comment by seankhl** [comment]
Material 3 and Material You would be fantastic. Speaking of themes, I'm wondering if the curtain-like background on the top left of the drawer will be removed as well. It seems unnecessary and looks garish to me (no offense intended to whoever added it).

**Comment by wmontwe** [comment]
We are working on Material3 and are refining some of the UI during that transition.

Referencing your comment on #7256 that version 6.711 already solved your issue, I 'll close this one.
